name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 Build Unsigned iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Ensure .env file exists
        run: |
          mkdir -p assets/env
          echo "API_URL=https://example.com" > assets/env/.env

      - name: Update CocoaPods
        run: pod repo update
        working-directory: ios

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Create Payload folder
        run: mkdir -p Payload
        working-directory: build/ios/iphoneos

      - name: Move app into Payload
        run: mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Package IPA
        run: zip -qq -r -9 VeeApp.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: VeeApp-ipa
          path: build/ios/iphoneos/VeeApp.ipa
